# Generated by Django 2.2.16 on 2022-02-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220218_1229'),
        ('reviews', '0002_auto_20220216_1816'),
    ]

    operations = [
    ]
