# Generated by Django 4.0.2 on 2022-02-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220219_0818'),
        ('reviews', '0008_auto_20220219_0953'),
    ]

    operations = [
    ]
